#Edge: BOTTOM
place_pin -pin_name req_msg[18] -layer metal6 -location {9.055 0} -force_to_die_boundary
place_pin -pin_name req_msg[19] -layer metal6 -location {15.775 0} -force_to_die_boundary
place_pin -pin_name req_msg[20] -layer metal6 -location {21.375 0} -force_to_die_boundary
place_pin -pin_name req_msg[25] -layer metal6 -location {16.895 0} -force_to_die_boundary
place_pin -pin_name req_msg[2] -layer metal6 -location {12.415 0} -force_to_die_boundary
place_pin -pin_name req_msg[3] -layer metal6 -location {18.015 0} -force_to_die_boundary
place_pin -pin_name req_msg[4] -layer metal6 -location {19.695 0} -force_to_die_boundary
place_pin -pin_name req_msg[5] -layer metal6 -location {29.215 0} -force_to_die_boundary
place_pin -pin_name resp_msg[0] -layer metal6 -location {12.975 0} -force_to_die_boundary
place_pin -pin_name resp_msg[1] -layer metal6 -location {14.655 0} -force_to_die_boundary
place_pin -pin_name resp_msg[2] -layer metal6 -location {13.535 0} -force_to_die_boundary
place_pin -pin_name resp_msg[3] -layer metal6 -location {18.575 0} -force_to_die_boundary
place_pin -pin_name resp_msg[4] -layer metal6 -location {24.175 0} -force_to_die_boundary
place_pin -pin_name resp_msg[5] -layer metal6 -location {23.615 0} -force_to_die_boundary
place_pin -pin_name resp_msg[9] -layer metal6 -location {19.135 0} -force_to_die_boundary
#Edge: RIGHT
place_pin -pin_name clk -layer metal5 -location {36.38 3.43} -force_to_die_boundary
place_pin -pin_name req_msg[21] -layer metal5 -location {36.38 7.91} -force_to_die_boundary
place_pin -pin_name req_msg[22] -layer metal5 -location {36.38 12.95} -force_to_die_boundary
place_pin -pin_name req_msg[23] -layer metal5 -location {36.38 19.11} -force_to_die_boundary
place_pin -pin_name req_msg[24] -layer metal5 -location {36.38 20.79} -force_to_die_boundary
place_pin -pin_name req_msg[6] -layer metal5 -location {36.38 10.71} -force_to_die_boundary
place_pin -pin_name req_msg[7] -layer metal5 -location {36.38 16.31} -force_to_die_boundary
place_pin -pin_name req_msg[8] -layer metal5 -location {36.38 18.55} -force_to_die_boundary
place_pin -pin_name resp_msg[6] -layer metal5 -location {36.38 12.39} -force_to_die_boundary
place_pin -pin_name resp_msg[7] -layer metal5 -location {36.38 15.75} -force_to_die_boundary
place_pin -pin_name resp_msg[8] -layer metal5 -location {36.38 16.87} -force_to_die_boundary
#Edge: TOP
place_pin -pin_name req_msg[13] -layer metal6 -location {9.055 36.38} -force_to_die_boundary
place_pin -pin_name req_msg[14] -layer metal6 -location {13.535 36.38} -force_to_die_boundary
place_pin -pin_name req_msg[15] -layer metal6 -location {15.775 36.38} -force_to_die_boundary
place_pin -pin_name req_msg[30] -layer metal6 -location {8.495 36.38} -force_to_die_boundary
place_pin -pin_name req_msg[31] -layer metal6 -location {5.695 36.38} -force_to_die_boundary
place_pin -pin_name resp_msg[10] -layer metal6 -location {24.175 36.38} -force_to_die_boundary
place_pin -pin_name resp_msg[11] -layer metal6 -location {18.575 36.38} -force_to_die_boundary
place_pin -pin_name resp_msg[12] -layer metal6 -location {27.535 36.38} -force_to_die_boundary
place_pin -pin_name resp_msg[13] -layer metal6 -location {20.255 36.38} -force_to_die_boundary
place_pin -pin_name resp_msg[14] -layer metal6 -location {23.615 36.38} -force_to_die_boundary
place_pin -pin_name resp_msg[15] -layer metal6 -location {21.375 36.38} -force_to_die_boundary
#Edge: LEFT
place_pin -pin_name req_msg[0] -layer metal5 -location {0 10.15} -force_to_die_boundary
place_pin -pin_name req_msg[10] -layer metal5 -location {0 21.35} -force_to_die_boundary
place_pin -pin_name req_msg[11] -layer metal5 -location {0 22.47} -force_to_die_boundary
place_pin -pin_name req_msg[12] -layer metal5 -location {0 25.27} -force_to_die_boundary
place_pin -pin_name req_msg[16] -layer metal5 -location {0 10.71} -force_to_die_boundary
place_pin -pin_name req_msg[17] -layer metal5 -location {0 7.91} -force_to_die_boundary
place_pin -pin_name req_msg[1] -layer metal5 -location {0 6.79} -force_to_die_boundary
place_pin -pin_name req_msg[26] -layer metal5 -location {0 21.91} -force_to_die_boundary
place_pin -pin_name req_msg[27] -layer metal5 -location {0 24.71} -force_to_die_boundary
place_pin -pin_name req_msg[28] -layer metal5 -location {0 26.95} -force_to_die_boundary
place_pin -pin_name req_msg[29] -layer metal5 -location {0 30.31} -force_to_die_boundary
place_pin -pin_name req_msg[9] -layer metal5 -location {0 18.55} -force_to_die_boundary
place_pin -pin_name req_rdy -layer metal5 -location {0 12.95} -force_to_die_boundary
place_pin -pin_name req_val -layer metal5 -location {0 13.51} -force_to_die_boundary
place_pin -pin_name reset -layer metal5 -location {0 15.19} -force_to_die_boundary
place_pin -pin_name resp_rdy -layer metal5 -location {0 14.07} -force_to_die_boundary
place_pin -pin_name resp_val -layer metal5 -location {0 14.63} -force_to_die_boundary
