#Edge: BOTTOM
place_pin -pin_name req_msg[23] -layer M5 -location {5.196 0} -force_to_die_boundary
place_pin -pin_name req_msg[24] -layer M5 -location {7.308 0} -force_to_die_boundary
place_pin -pin_name req_msg[25] -layer M5 -location {8.94 0} -force_to_die_boundary
place_pin -pin_name req_msg[7] -layer M5 -location {5.388 0} -force_to_die_boundary
place_pin -pin_name req_msg[8] -layer M5 -location {7.116 0} -force_to_die_boundary
place_pin -pin_name req_msg[9] -layer M5 -location {8.46 0} -force_to_die_boundary
place_pin -pin_name resp_msg[10] -layer M5 -location {7.98 0} -force_to_die_boundary
place_pin -pin_name resp_msg[15] -layer M5 -location {10.284 0} -force_to_die_boundary
place_pin -pin_name resp_msg[7] -layer M5 -location {5.772 0} -force_to_die_boundary
place_pin -pin_name resp_msg[8] -layer M5 -location {7.212 0} -force_to_die_boundary
place_pin -pin_name resp_msg[9] -layer M5 -location {9.036 0} -force_to_die_boundary
#Edge: RIGHT
place_pin -pin_name req_msg[12] -layer M4 -location {16.2 10.764} -force_to_die_boundary
place_pin -pin_name req_msg[13] -layer M4 -location {16.2 9.42} -force_to_die_boundary
place_pin -pin_name req_msg[14] -layer M4 -location {16.2 8.94} -force_to_die_boundary
place_pin -pin_name req_msg[28] -layer M4 -location {16.2 10.476} -force_to_die_boundary
place_pin -pin_name req_msg[30] -layer M4 -location {16.2 7.5} -force_to_die_boundary
place_pin -pin_name req_msg[31] -layer M4 -location {16.2 7.596} -force_to_die_boundary
place_pin -pin_name resp_msg[11] -layer M4 -location {16.2 5.676} -force_to_die_boundary
place_pin -pin_name resp_msg[12] -layer M4 -location {16.2 9.9} -force_to_die_boundary
place_pin -pin_name resp_msg[13] -layer M4 -location {16.2 8.652} -force_to_die_boundary
place_pin -pin_name resp_msg[14] -layer M4 -location {16.2 7.308} -force_to_die_boundary
#Edge: TOP
place_pin -pin_name req_msg[0] -layer M5 -location {8.268 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[10] -layer M5 -location {7.884 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[11] -layer M5 -location {11.148 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[15] -layer M5 -location {8.844 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[16] -layer M5 -location {9.42 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[17] -layer M5 -location {6.636 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[1] -layer M5 -location {7.02 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[27] -layer M5 -location {10.476 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[29] -layer M5 -location {9.228 16.2} -force_to_die_boundary
place_pin -pin_name req_msg[2] -layer M5 -location {7.692 16.2} -force_to_die_boundary
place_pin -pin_name req_val -layer M5 -location {9.804 16.2} -force_to_die_boundary
place_pin -pin_name reset -layer M5 -location {10.092 16.2} -force_to_die_boundary
place_pin -pin_name resp_msg[0] -layer M5 -location {8.172 16.2} -force_to_die_boundary
place_pin -pin_name resp_msg[1] -layer M5 -location {6.54 16.2} -force_to_die_boundary
place_pin -pin_name resp_msg[2] -layer M5 -location {5.964 16.2} -force_to_die_boundary
place_pin -pin_name resp_rdy -layer M5 -location {10.188 16.2} -force_to_die_boundary
place_pin -pin_name resp_val -layer M5 -location {10.284 16.2} -force_to_die_boundary
#Edge: LEFT
place_pin -pin_name clk -layer M4 -location {0 12.876} -force_to_die_boundary
place_pin -pin_name req_msg[18] -layer M4 -location {0 11.052} -force_to_die_boundary
place_pin -pin_name req_msg[19] -layer M4 -location {0 9.996} -force_to_die_boundary
place_pin -pin_name req_msg[20] -layer M4 -location {0 8.172} -force_to_die_boundary
place_pin -pin_name req_msg[21] -layer M4 -location {0 6.924} -force_to_die_boundary
place_pin -pin_name req_msg[22] -layer M4 -location {0 5.484} -force_to_die_boundary
place_pin -pin_name req_msg[26] -layer M4 -location {0 7.692} -force_to_die_boundary
place_pin -pin_name req_msg[3] -layer M4 -location {0 10.092} -force_to_die_boundary
place_pin -pin_name req_msg[4] -layer M4 -location {0 8.556} -force_to_die_boundary
place_pin -pin_name req_msg[5] -layer M4 -location {0 6.828} -force_to_die_boundary
place_pin -pin_name req_msg[6] -layer M4 -location {0 4.236} -force_to_die_boundary
place_pin -pin_name req_rdy -layer M4 -location {0 11.34} -force_to_die_boundary
place_pin -pin_name resp_msg[3] -layer M4 -location {0 9.804} -force_to_die_boundary
place_pin -pin_name resp_msg[4] -layer M4 -location {0 8.46} -force_to_die_boundary
place_pin -pin_name resp_msg[5] -layer M4 -location {0 7.116} -force_to_die_boundary
place_pin -pin_name resp_msg[6] -layer M4 -location {0 7.02} -force_to_die_boundary
